### ISSUE TITLE
 samples of genes

### ISSUE THREAD

**Issue by Vector-DLIX** [bdew/gendustry#234]
JEI is not showing samples of genes , that is, their classification ,how to fix it? gendustry 1.10.2

**Comment by bdew** [comment]
What do you mean their classification?..

**Comment by Vector-DLIX** [comment]
![1](https://user-images.githubusercontent.com/33153866/32143739-f3929cf8-bccf-11e7-891d-b5b60e44e8a8.png)

**Comment by bdew** [comment]
Ah i see, it's a problem with the localization. At some point i made the species and allele show up in the name of the item, and added placeholders for that:

item.gendustry.GeneSample.name=%s Sample - %s

But Russian (and some other) localization wasn't updated, so it doesn't add that part.

I'm fixing the russian localization

![image](https://user-images.githubusercontent.com/96327/32143873-10e387c0-bcb9-11e7-9166-c880c59ca52b.png)

For the other localizations i'll just append it to the name, it'd be nice for people speaking the languages to look at it and tell me if it makes sense or needs changing.

The way it works is there are 2 %s placeholders, the first one will be replace by gendustry.label.sample.root* string based on the species, the second one by the chromosome name (gendustry.chromosome.*) and allele value (in Forestry localisation for those that need them).

**Comment by bdew** [comment]
The fix for now will be for 1.12 version only, i'll give a few days for people to chime in about the other localisations then make an update for earlier versions too.

**Comment by Vector-DLIX** [comment]
то есть можно просто переключится на английский перевод и появятся?

**Comment by bdew** [comment]
Yes in English it shows correctly.

**Comment by Vector-DLIX** [comment]
можете сделать обновление с русскоязычным переводом?

**Comment by bdew** [comment]
As i've said, for MC 1.12.x it's fixed now (new build will be on CurseForge in a few minutes). For earlier versions i'll make an update in a few days so that people can look at the other languages and fix if need be.


Как я сказал выше, для MC 1.12.x теперь исправлено (новый билд будет на CurseForge через несколько минут). Для более ранних версий я сделаю обновление через несколько дней, чтобы люди смогли проверить другие языки и исправить, если это необходимо.

**Comment by Vector-DLIX** [comment]
спасибо)

**Comment by bdew** [comment]
Updates for older versions:

* [Gendustry 1.6.5.32 (MC 1.10.2)](https://minecraft.curseforge.com/projects/gendustry/files/2498424)
* [Gendustry 1.6.5.10 (MC 1.11.2) ](https://minecraft.curseforge.com/projects/gendustry/files/2498420)
